sonar.projectKey=github.com/cloudfstrife/levenshtein
sonar.projectName=levenshtein
sonar.projectVersion=v1.3.0

sonar.sources=.

## ----------------------------------------------------
## go test -coverprofile=testing/coverprofile
## sonar-scanner
## ----------------------------------------------------
sonar.go.coverage.reportPaths=./testing/coverprofile

sonar.sourceEncoding=UTF-8