sonar.projectKey=github.com/cloudfstrife/levenshtein
sonar.projectName=levenshtein
sonar.projectVersion=v1.3.1

sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/vendor/**

## ----------------------------------------------------
## go test -coverprofile=testing/coverprofile
## sonar-scanner
## ----------------------------------------------------
sonar.go.coverage.reportPaths=./testing/coverprofile